# Generated by Django 4.2.7 on 2023-12-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventSearch', '0004_band_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
